# Core
add_subdirectory(wireless_core_backend)
add_subdirectory(common_backend)

if (USB_AUDIO_ENABLED AND NOT(RTOS_ENABLED))
    if (APP STREQUAL "Audio-Bidirectional")
        add_subdirectory(audio_bidirectional_backend)
        add_subdirectory(audio_core_backend)
    elseif (APP STREQUAL "Audio-Unidirectional")
        add_subdirectory(audio_unidirectional_backend)
        add_subdirectory(audio_core_backend)
    elseif (APP STREQUAL "Puretone-Headset")
        add_subdirectory(puretone_headset_backend)
        add_subdirectory(audio_core_backend)
    elseif (APP STREQUAL "All")
        add_subdirectory(audio_bidirectional_backend)
        add_subdirectory(audio_unidirectional_backend)
        add_subdirectory(puretone_headset_backend)
        add_subdirectory(audio_core_backend)
    endif()
    return()
endif()

# SDK Example Application
if (APP STREQUAL "Connection-Priority")
    add_subdirectory(connection_priority_backend)
elseif (APP STREQUAL "Audio-Bidirectional")
    add_subdirectory(audio_bidirectional_backend)
    add_subdirectory(audio_core_backend)
elseif (APP STREQUAL "Audio-Unidirectional")
    add_subdirectory(audio_unidirectional_backend)
    add_subdirectory(audio_core_backend)
elseif (APP STREQUAL "Datalink")
    add_subdirectory(datalink_backend)
elseif (APP STREQUAL "Fragmentation")
    add_subdirectory(fragmentation_backend)
elseif (APP STREQUAL "Hello-World")
    add_subdirectory(hello_world_backend)
elseif (APP STREQUAL "Hello-World-RTOS")
    add_subdirectory(hello_world_rtos_backend)
elseif (APP STREQUAL "Puretone-Headset")
    add_subdirectory(puretone_headset_backend)
    add_subdirectory(audio_core_backend)
elseif (APP STREQUAL "Star-Network")
    add_subdirectory(star_network_backend)
elseif (APP STREQUAL "BSP-validator")
    add_subdirectory(bsp_validator_backend)
elseif (APP STREQUAL "Profiler")
    add_subdirectory(profiler_backend)
elseif (APP STREQUAL "All")
    if (RTOS_ENABLED)
        add_subdirectory(hello_world_rtos_backend)
    else()
        if(TRANSCEIVER STREQUAL "SR1100")
            add_subdirectory(puretone_headset_backend)
        endif()
        add_subdirectory(connection_priority_backend)
        add_subdirectory(audio_bidirectional_backend)
        add_subdirectory(audio_unidirectional_backend)
        add_subdirectory(datalink_backend)
        add_subdirectory(fragmentation_backend)
        add_subdirectory(hello_world_backend)
        add_subdirectory(star_network_backend)
        add_subdirectory(bsp_validator_backend)
        add_subdirectory(profiler_backend)
        add_subdirectory(audio_core_backend)
    endif()
endif()
