#!/usr/bin/env python3

import os, platform, subprocess, sys
from pathlib import Path
import shutil
import time

script_path = os.path.dirname(os.path.realpath(__file__))

if platform.system() == "Linux":
    encoding = "utf-8"
    dfu_util_path = "dfu-util"
elif platform.system() == "Windows":
    from subprocess import CREATE_NO_WINDOW
    encoding = "cp437"
    dfu_util_path = "dfu-util.exe"

    output = subprocess.check_output(["pnputil", "/enum-drivers"], creationflags=CREATE_NO_WINDOW).decode(encoding)
    if "stm32bootloader.inf" in output or "USB\VID_0483&PID_DF11 (libwdi autogenerated)" in output:
        print("STM32 Driver found")
    else:
        print("STM32bootloader Driver is missing. Installing...")
        result = subprocess.run(["install-drivers.bat"], creationflags=CREATE_NO_WINDOW)
        max_wait = 10
        elapsed = 0
        while elapsed < max_wait:
            output = subprocess.check_output(["pnputil", "/enum-drivers"], creationflags=CREATE_NO_WINDOW).decode(encoding)
            if "stm32bootloader.inf" in output or "USB\VID_0483&PID_DF11 (libwdi autogenerated)" in output:
                print("STM32 Driver found")
                break
            time.sleep(1)
            elapsed += 1
        else:
            sys.exit("Error: Driver installation timeout - driver not found after 10 seconds")
        if result.returncode != 0:
            sys.exit("Error: Driver installation failed")
else:
    sys.exit("Error: Not supported on this operating system")

if not shutil.which(dfu_util_path):
    sys.exit(f"Error: dfu-util executable not found in PATH")


def main():
    HELP = "Set the path to the binary to be flashed on the device as argument.\r\n" + \
       " Note: .elf files path will be replaced by .bin path\r\n" + \
       " ex: `python dfu-util.py <path_to_bin.elf>`"

    # If no options are given, find .elf files and prompt user
    if len(sys.argv) == 1:
        print("Searching for .elf files in build directory...")
        elf_files = []
        for root, dirs, files in os.walk("build"):
            for file in files:
                if file.endswith(".elf") and "CMake" not in root:
                    elf_files.append(os.path.join(root, file))

        if not elf_files:
            print("No .elf files found in build/ directory.")
            print(HELP)
            return

        print("\nAvailable binaries:")
        for i, f in enumerate(elf_files):
            print(f"  [{i+1}] {f}")

        try:
            selection = input("\nSelect a binary number to flash: ")
            index = int(selection) - 1
            if 0 <= index < len(elf_files):
                binary_path = elf_files[index]
            else:
                print("Invalid selection.")
                return
        except ValueError:
            print("Invalid input.")
            return
    else:
        binary_path = sys.argv[1]

    print(f"\nFlashing: {binary_path}")

    # Change the file path to a .bin file (vscode task will pass a .elf).
    file_path = binary_path
    filename = file_path.rsplit(".", 1)
    if len(filename) > 1:
        bin_path = f"{filename[0]}.bin"
    else:
        bin_path = f"{filename[0]}.bin"

    args = (f"{dfu_util_path}", "-a0", "-i0", "-s0x08000000:mass-erase:force:fast:leave", f"-D{bin_path}")

    with subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE) as p:
        while True:
            text = p.stdout.read1().decode(encoding)
            print(text, end='', flush=True)
            if p.poll() is not None:
                break

        errors = p.stderr.read1().decode(encoding).split('\n')
        for error in errors:
            if "No DFU capable USB device available" in error:
                # Other errors are filtered out since there were errors messages on leave.
                if platform.system() == "Windows":
                    print(error + "\r\n  => Make sure USB DFU Drivers are installed")
                elif platform.system() == "Linux":
                    print(error + "\n  => Make sure you have the right permissions to access USB devices.\n" +
                          "     You may need to create a udev rule.")
                else:
                    print(error)
if __name__ == '__main__':
    main()
