/** @file  quasar_def.h
 *  @brief This file defines MCU pinout and other control definitions.
 *
 *  @copyright Copyright (C) 2026 SPARK Microsystems International Inc. All rights reserved.
 *  @license   This source code is proprietary and subject to the SPARK Microsystems
 *             Software EULA found in this package in file EULA.txt.
 *  @author    SPARK FW Team.
 */
#ifndef QUASAR_DEF_H_
#define QUASAR_DEF_H_

/* INCLUDES *******************************************************************/
#include "stm32u5xx_hal.h"
#include "quasar_gpio.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CONSTANTS ******************************************************************/
/*! RADIO 1 MAPPING. */
#define QUASAR_DEF_RADIO_1_SCK_PORT      GPIOE
#define QUASAR_DEF_RADIO_1_SCK_PIN       QUASAR_GPIO_PIN_13
#define QUASAR_DEF_RADIO_1_MOSI_PORT     GPIOE
#define QUASAR_DEF_RADIO_1_MOSI_PIN      QUASAR_GPIO_PIN_15
#define QUASAR_DEF_RADIO_1_MISO_PORT     GPIOE
#define QUASAR_DEF_RADIO_1_MISO_PIN      QUASAR_GPIO_PIN_14
#define QUASAR_DEF_RADIO_1_CS_PORT       GPIOE
#define QUASAR_DEF_RADIO_1_CS_PIN        QUASAR_GPIO_PIN_11
#ifdef QUASAR_U535_91EVB
#define QUASAR_DEF_RADIO_1_RESET_PORT    GPIOA  /* PA1 per 91_535_evb */
#define QUASAR_DEF_RADIO_1_RESET_PIN     QUASAR_GPIO_PIN_1
#else
#define QUASAR_DEF_RADIO_1_RESET_PORT    GPIOE  /* PE10 default */
#define QUASAR_DEF_RADIO_1_RESET_PIN     QUASAR_GPIO_PIN_10
#endif
#define QUASAR_DEF_RADIO_1_SHUTDOWN_PORT GPIOD
#define QUASAR_DEF_RADIO_1_SHUTDOWN_PIN  QUASAR_GPIO_PIN_9
#define QUASAR_DEF_RADIO_1_IRQ_PORT      GPIOE
#define QUASAR_DEF_RADIO_1_IRQ_PIN       QUASAR_GPIO_PIN_8

/*! With the SR11x0 this pin may be used as VDDIO for the radio on the demo board. */
#define QUASAR_DEF_RADIO_1_DBG_EN_PORT       GPIOD
#define QUASAR_DEF_RADIO_1_DBG_EN_PIN        QUASAR_GPIO_PIN_13
#define QUASAR_DEF_RADIO_1_SCN_EN_PORT       GPIOD
#define QUASAR_DEF_RADIO_1_SCN_EN_PIN        QUASAR_GPIO_PIN_10
// #define QUASAR_DEF_RADIO_1_PLL_SEL_PORT      GPIOC
// #define QUASAR_DEF_RADIO_1_PLL_SEL_PIN       QUASAR_GPIO_PIN_6
// #define QUASAR_DEF_RADIO_1_CLK_XTAL_SEL_PORT GPIOC
// #define QUASAR_DEF_RADIO_1_CLK_XTAL_SEL_PIN  QUASAR_GPIO_PIN_7

/*! RADIO 2 MAPPING. */
// #define QUASAR_DEF_RADIO_2_SCK_PORT       GPIOB
// #define QUASAR_DEF_RADIO_2_SCK_PIN        QUASAR_GPIO_PIN_10
// #define QUASAR_DEF_RADIO_2_MOSI_PORT_REVA GPIOB
// #define QUASAR_DEF_RADIO_2_MOSI_PIN_REVA  QUASAR_GPIO_PIN_15
// #define QUASAR_DEF_RADIO_2_MOSI_PORT_REVB GPIOD
// #define QUASAR_DEF_RADIO_2_MOSI_PIN_REVB  QUASAR_GPIO_PIN_4
// #define QUASAR_DEF_RADIO_2_MISO_PORT      GPIOB
// #define QUASAR_DEF_RADIO_2_MISO_PIN       QUASAR_GPIO_PIN_14
// #define QUASAR_DEF_RADIO_2_CS_PORT        GPIOI
// #define QUASAR_DEF_RADIO_2_CS_PIN         QUASAR_GPIO_PIN_5
// #define QUASAR_DEF_RADIO_2_RESET_PORT     GPIOD
// #define QUASAR_DEF_RADIO_2_RESET_PIN      QUASAR_GPIO_PIN_8
// #define QUASAR_DEF_RADIO_2_SHUTDOWN_PORT  GPIOD
// #define QUASAR_DEF_RADIO_2_SHUTDOWN_PIN   QUASAR_GPIO_PIN_11
// #define QUASAR_DEF_RADIO_2_IRQ_PORT       GPIOE
// #define QUASAR_DEF_RADIO_2_IRQ_PIN        QUASAR_GPIO_PIN_7

// #define QUASAR_DEF_RADIO_2_IO_4_PORT      GPIOB
// #define QUASAR_DEF_RADIO_2_IO_4_PIN       QUASAR_GPIO_PIN_13

/*! QSPI Radio 1 (OCTOSPI1). */
// #define QUASAR_DEF_RADIO_1_QSPI_SCK_PORT  GPIOF
// #define QUASAR_DEF_RADIO_1_QSPI_SCK_PIN   QUASAR_GPIO_PIN_10
// #define QUASAR_DEF_RADIO_1_QSPI_IO_0_PORT GPIOF
// #define QUASAR_DEF_RADIO_1_QSPI_IO_0_PIN  QUASAR_GPIO_PIN_8
// #define QUASAR_DEF_RADIO_1_QSPI_IO_1_PORT GPIOF
// #define QUASAR_DEF_RADIO_1_QSPI_IO_1_PIN  QUASAR_GPIO_PIN_9
// #define QUASAR_DEF_RADIO_1_QSPI_IO_2_PORT GPIOF
// #define QUASAR_DEF_RADIO_1_QSPI_IO_2_PIN  QUASAR_GPIO_PIN_7
// #define QUASAR_DEF_RADIO_1_QSPI_IO_3_PORT GPIOF
// #define QUASAR_DEF_RADIO_1_QSPI_IO_3_PIN  QUASAR_GPIO_PIN_6

// /*! QSPI Radio 2 (OCTOSPI2). */
// #define QUASAR_DEF_RADIO_2_QSPI_SCK_PORT  GPIOH
// #define QUASAR_DEF_RADIO_2_QSPI_SCK_PIN   QUASAR_GPIO_PIN_6
// #define QUASAR_DEF_RADIO_2_QSPI_IO_0_PORT GPIOI
// #define QUASAR_DEF_RADIO_2_QSPI_IO_0_PIN  QUASAR_GPIO_PIN_3
// #define QUASAR_DEF_RADIO_2_QSPI_IO_1_PORT GPIOI
// #define QUASAR_DEF_RADIO_2_QSPI_IO_1_PIN  QUASAR_GPIO_PIN_2
// #define QUASAR_DEF_RADIO_2_QSPI_IO_2_PORT GPIOI
// #define QUASAR_DEF_RADIO_2_QSPI_IO_2_PIN  QUASAR_GPIO_PIN_1
// #define QUASAR_DEF_RADIO_2_QSPI_IO_3_PORT GPIOH
// #define QUASAR_DEF_RADIO_2_QSPI_IO_3_PIN  QUASAR_GPIO_PIN_8

/*! Audio module     I2C2 // SAI1. */
#define QUASAR_DEF_AUDIO_I2C_SDA_PORT  GPIOB
#define QUASAR_DEF_AUDIO_I2C_SDA_PIN   QUASAR_GPIO_PIN_3
#define QUASAR_DEF_AUDIO_I2C_SCL_PORT  GPIOB
#define QUASAR_DEF_AUDIO_I2C_SCL_PIN   QUASAR_GPIO_PIN_6

#define QUASAR_DEF_AUDIO_SAI_SD_A_PORT GPIOC
#define QUASAR_DEF_AUDIO_SAI_SD_A_PIN  QUASAR_GPIO_PIN_1
#define QUASAR_DEF_AUDIO_SAI_SCK_PORT  GPIOE
#define QUASAR_DEF_AUDIO_SAI_SCK_PIN   QUASAR_GPIO_PIN_5
#define QUASAR_DEF_AUDIO_SAI_MCLK_PORT GPIOB
#define QUASAR_DEF_AUDIO_SAI_MCLK_PIN  QUASAR_GPIO_PIN_8
#define QUASAR_DEF_AUDIO_SAI_SD_B_PORT GPIOB
#define QUASAR_DEF_AUDIO_SAI_SD_B_PIN  QUASAR_GPIO_PIN_5
#define QUASAR_DEF_AUDIO_SAI_FS_PORT   GPIOB
#define QUASAR_DEF_AUDIO_SAI_FS_PIN    QUASAR_GPIO_PIN_9

#define QUASAR_DEF_AUDIO_IRQ_PORT      GPIOE
#define QUASAR_DEF_AUDIO_IRQ_PIN       QUASAR_GPIO_PIN_9

/** If I2S is needed on the expansion port, the MUX_SEL pin
 *  should be set to HIGH. By default, the I2S signals are
 *  only connected to the onboard codec and the GPIO MUX_SEL
 *  is pulled down with a resistor.
 *  U535: PC2 is NC on this board — I2S goes directly to expansion port pins.
 *  Codec connection requires a jumper; no MUX GPIO control needed.
 */
// #define QUASAR_DEF_I2S_MUX_SEL_PORT GPIOC
// #define QUASAR_DEF_I2S_MUX_SEL_PIN  QUASAR_GPIO_PIN_2

/*! EEPROM   I2C1. */
// #define QUASAR_DEF_EEPROM_SCL_PORT     GPIOB
// #define QUASAR_DEF_EEPROM_SCL_PIN      QUASAR_GPIO_PIN_6
// #define QUASAR_DEF_EEPROM_SDA_PORT     GPIOB
// #define QUASAR_DEF_EEPROM_SDA_PIN      QUASAR_GPIO_PIN_3
// #define QUASAR_DEF_EEPROM_RADIO_1_ADDR 0xA2
// #define QUASAR_DEF_EEPROM_RADIO_2_ADDR 0xA0

/*! UI. */
#define QUASAR_DEF_BUTTON_USER_1_PORT GPIOA
#define QUASAR_DEF_BUTTON_USER_1_PIN  QUASAR_GPIO_PIN_4
// #define QUASAR_DEF_BUTTON_USER_2_PORT GPIOH
// #define QUASAR_DEF_BUTTON_USER_2_PIN  QUASAR_GPIO_PIN_12
// #define QUASAR_DEF_BUTTON_USER_3_PORT GPIOH
// #define QUASAR_DEF_BUTTON_USER_3_PIN  QUASAR_GPIO_PIN_15
// #define QUASAR_DEF_BUTTON_USER_4_PORT GPIOI
// #define QUASAR_DEF_BUTTON_USER_4_PIN  QUASAR_GPIO_PIN_0

// #define QUASAR_DEF_LED_USER_1_PORT    GPIOA  // PA1 = RADIO_1_RESET, conflict
// #define QUASAR_DEF_LED_USER_1_PIN     QUASAR_GPIO_PIN_1
// #define QUASAR_DEF_LED_USER_2_PORT    GPIOD  // PD0 = BAT_CHRG_TS, conflict
// #define QUASAR_DEF_LED_USER_2_PIN     QUASAR_GPIO_PIN_0
// #define QUASAR_DEF_LED_USER_3_PORT    GPIOG
// #define QUASAR_DEF_LED_USER_3_PIN     QUASAR_GPIO_PIN_15
// #define QUASAR_DEF_LED_USER_4_PORT    GPIOI
// #define QUASAR_DEF_LED_USER_4_PIN     QUASAR_GPIO_PIN_6
#define QUASAR_DEF_LED_USB_PORT       GPIOB
#define QUASAR_DEF_LED_USB_PIN        QUASAR_GPIO_PIN_2
// #define QUASAR_DEF_LED_LINEIN_PORT    GPIOI
// #define QUASAR_DEF_LED_LINEIN_PIN     QUASAR_GPIO_PIN_7
// #define QUASAR_DEF_LED_HP_JACK_PORT   GPIOH
// #define QUASAR_DEF_LED_HP_JACK_PIN    QUASAR_GPIO_PIN_14
// #define QUASAR_DEF_LED_RGB_GREEN_PORT GPIOB
// #define QUASAR_DEF_LED_RGB_GREEN_PIN  QUASAR_GPIO_PIN_4
#define QUASAR_DEF_LED_RGB_BLUE_PORT  GPIOD
#define QUASAR_DEF_LED_RGB_BLUE_PIN   QUASAR_GPIO_PIN_7
// #define QUASAR_DEF_LED_RGB_RED_PORT   GPIOH
// #define QUASAR_DEF_LED_RGB_RED_PIN    QUASAR_GPIO_PIN_11

/*! Power management and monitoring. */
#define QUASAR_DEF_BAT_CHRG_PORT         GPIOC
#define QUASAR_DEF_BAT_CHRG_PIN          QUASAR_GPIO_PIN_13
#define QUASAR_DEF_BAT_CHRG_TS_PORT      GPIOD
#define QUASAR_DEF_BAT_CHRG_TS_PIN       QUASAR_GPIO_PIN_0
#define QUASAR_DEF_BOOT_INDICATOR_PORT   GPIOB
#define QUASAR_DEF_BOOT_INDICATOR_PIN    QUASAR_GPIO_PIN_11
#define QUASAR_DEF_LINEIN_DETECT_PORT    GPIOD
#define QUASAR_DEF_LINEIN_DETECT_PIN     QUASAR_GPIO_PIN_3
#define QUASAR_DEF_USB_5V_IN_DETECT_PORT GPIOC
#define QUASAR_DEF_USB_5V_IN_DETECT_PIN  QUASAR_GPIO_PIN_12
#define QUASAR_DEF_LDO_MCU_EN_PORT_REVA  GPIOD
#define QUASAR_DEF_LDO_MCU_EN_PIN_REVA   QUASAR_GPIO_PIN_4
#define QUASAR_DEF_LDO_MCU_EN_PORT_REVB  GPIOB
#define QUASAR_DEF_LDO_MCU_EN_PIN_REVB   QUASAR_GPIO_PIN_15
// #define QUASAR_DEF_LDO_LED_EN_PORT       GPIOI
// #define QUASAR_DEF_LDO_LED_EN_PIN        QUASAR_GPIO_PIN_4
#define QUASAR_DEF_VDD_SEL_PORT          GPIOD
#define QUASAR_DEF_VDD_SEL_PIN           QUASAR_GPIO_PIN_14
#define QUASAR_DEF_NVM_EN_PORT           GPIOB
#define QUASAR_DEF_NVM_EN_PIN            QUASAR_GPIO_PIN_12
#define QUASAR_DEF_ADC_BAT_PORT          GPIOA
#define QUASAR_DEF_ADC_BAT_PIN           QUASAR_GPIO_PIN_6
// #define QUASAR_DEF_ADC_BOARD_REV_PORT    GPIOC
// #define QUASAR_DEF_ADC_BOARD_REV_PIN     QUASAR_GPIO_PIN_0

/** ADC peripheral and channel selection
 *  PC0 (Board revision) -> ADC1_IN1
 *  PA6 (Battery level)  -> ADC1_IN11
 */
#define QUASAR_DEF_ADC_SELECTION_BATTERY_VOLTAGE QUASAR_ADC_PERIPHERAL_1
#define QUASAR_DEF_ADC_SELECTION_BOARD_REVISION  QUASAR_ADC_PERIPHERAL_1
#define QUASAR_DEF_ADC_CHANNEL_BATTERY_VOLTAGE   QUASAR_ADC_CHANNEL_11
#define QUASAR_DEF_ADC_CHANNEL_BOARD_REVISION    QUASAR_ADC_CHANNEL_1

#define QUASAR_DEF_STLINK_UART_TX_PORT           GPIOC
#define QUASAR_DEF_STLINK_UART_TX_PIN            QUASAR_GPIO_PIN_10
#define QUASAR_DEF_STLINK_UART_RX_PORT           GPIOC
#define QUASAR_DEF_STLINK_UART_RX_PIN            QUASAR_GPIO_PIN_11

/*! Expansion port IO used as debug IO. */
#define QUASAR_DEF_DEBUG_IO_0_PORT         GPIOA
#define QUASAR_DEF_DEBUG_IO_0_PIN          QUASAR_GPIO_PIN_4
// #define QUASAR_DEF_DEBUG_IO_1_PORT         GPIOA
// #define QUASAR_DEF_DEBUG_IO_1_PIN          QUASAR_GPIO_PIN_5
// #define QUASAR_DEF_DEBUG_IO_2_PORT         GPIOC
// #define QUASAR_DEF_DEBUG_IO_2_PIN          QUASAR_GPIO_PIN_3
// #define QUASAR_DEF_DEBUG_IO_3_PORT         GPIOC
// #define QUASAR_DEF_DEBUG_IO_3_PIN          QUASAR_GPIO_PIN_5
// #define QUASAR_DEF_DEBUG_IO_4_PORT         GPIOB
// #define QUASAR_DEF_DEBUG_IO_4_PIN          QUASAR_GPIO_PIN_1

#define QUASAR_DEF_EXPANSION_UART_TX_PORT  GPIOA
#define QUASAR_DEF_EXPANSION_UART_TX_PIN   QUASAR_GPIO_PIN_2
#define QUASAR_DEF_EXPANSION_UART_RX_PORT  GPIOA
#define QUASAR_DEF_EXPANSION_UART_RX_PIN   QUASAR_GPIO_PIN_3
// #define QUASAR_DEF_EXPANSION_SPI_CS_PORT   GPIOA
// #define QUASAR_DEF_EXPANSION_SPI_CS_PIN    QUASAR_GPIO_PIN_15
// #define QUASAR_DEF_EXPANSION_SPI_MOSI_PORT GPIOD
// #define QUASAR_DEF_EXPANSION_SPI_MOSI_PIN  QUASAR_GPIO_PIN_6
// #define QUASAR_DEF_EXPANSION_SPI_SCK_PORT  GPIOG
// #define QUASAR_DEF_EXPANSION_SPI_SCK_PIN   QUASAR_GPIO_PIN_9
// #define QUASAR_DEF_EXPANSION_SPI_MISO_PORT GPIOG
// #define QUASAR_DEF_EXPANSION_SPI_MISO_PIN  QUASAR_GPIO_PIN_10

/*! Priorities. */
#define QUASAR_DEF_PRIO_MULTI_RADIO_TIMER_IRQ QUASAR_IRQ_PRIORITY_0
#define QUASAR_DEF_PRIO_AUDIO_SAI_DMA_TX_IRQ  QUASAR_IRQ_PRIORITY_1
#define QUASAR_DEF_PRIO_AUDIO_SAI_DMA_RX_IRQ  QUASAR_IRQ_PRIORITY_1
#define QUASAR_DEF_PRIO_RADIO_1_IRQ           QUASAR_IRQ_PRIORITY_2
#define QUASAR_DEF_PRIO_RADIO_2_IRQ           QUASAR_IRQ_PRIORITY_2
#define QUASAR_DEF_PRIO_RADIO_1_DMA_IRQ       QUASAR_IRQ_PRIORITY_2
#define QUASAR_DEF_PRIO_RADIO_2_DMA_IRQ       QUASAR_IRQ_PRIORITY_2
#define FREE_RUNNING_TIMER_PRIORITY           QUASAR_IRQ_PRIORITY_3
#define QUASAR_DEF_PRIO_OTG_HS_IRQ            QUASAR_IRQ_PRIORITY_8
#define QUASAR_DEF_PRIO_USB_DETECT_IRQ        QUASAR_IRQ_PRIORITY_11
#define QUASAR_DEF_PRIO_PENDSV_IRQ            QUASAR_IRQ_PRIORITY_12
#define QUASAR_DEF_PRIO_TIMER_NO_IRQ          QUASAR_IRQ_PRIORITY_NONE

/*! DMA Controller channel (SAI has not been converted to use DMA driver instead of HAL). */
#define QUASAR_DEF_DMA_SELECTION_RADIO_1_TX QUASAR_DMA_SELECTION_GPDMA1_CHANNEL1
#define QUASAR_DEF_DMA_SELECTION_RADIO_1_RX QUASAR_DMA_SELECTION_GPDMA1_CHANNEL2
#define QUASAR_DEF_DMA_SELECTION_RADIO_2_TX QUASAR_DMA_SELECTION_GPDMA1_CHANNEL5
#define QUASAR_DEF_DMA_SELECTION_RADIO_2_RX QUASAR_DMA_SELECTION_GPDMA1_CHANNEL6
#define QUASAR_DEF_GPDMA1_CHANNEL_SAI_TX    GPDMA1_Channel7
#define QUASAR_DEF_GPDMA1_CHANNEL_SAI_RX    GPDMA1_Channel8

/*! Nested vectored interrupt controller ID. */
#define QUASAR_NVIC_SAI_DMA_TX_CPLT GPDMA1_Channel7_IRQn
#define QUASAR_NVIC_SAI_DMA_RX_CPLT GPDMA1_Channel8_IRQn

/*! Peripherals selection (SAI driver has not been implemented. SAI selection is directly in quasar_audio file). */
#define QUASAR_DEF_SPI_SELECTION_RADIO_1      QUASAR_SPI_SELECTION_SPI1
#define QUASAR_DEF_SPI_SELECTION_RADIO_2      QUASAR_SPI_SELECTION_SPI2
#define QUASAR_DEF_QSPI_SELECTION_RADIO_1     QUASAR_QSPI_SELECTION_OSPI1
#define QUASAR_DEF_QSPI_SELECTION_RADIO_2     QUASAR_QSPI_SELECTION_OSPI2
#define QUASAR_DEF_I2C_SELECTON_EEROM_RADIO_1 QUASAR_I2C_SELECTION_I2C1
#define QUASAR_DEF_I2C_SELECTION_CODEC        QUASAR_I2C_SELECTION_I2C2

/* U535: USART2 does not exist on STM32U535xx. PA2/PA3 (expansion port) have no
 *       available UART via AF7 on this device. Expansion UART is not supported.
 *       All quasar_uart_* calls with QUASAR_UART_SELECTION_USART2 are silently
 *       no-op'd by the NULL guard in quasar_uart.c. */
// #define QUASAR_DEF_UART_SELECTION_EXPANSION   QUASAR_UART_SELECTION_USART2
#define QUASAR_DEF_SPI_SELECTION_EXPANSION    QUASAR_SPI_SELECTION_SPI3
#define QUASAR_DEF_UART_SELECTION_DEBUG       QUASAR_UART_SELECTION_UART4

/*! Timer selection. */
#define QUASAR_DEF_TIMER_SELECTION_FREE_RUNNING_MS QUASAR_TIMER_SELECTION_TIMER8
#define QUASAR_DEF_TIMER_SELECTION_MULTI_RADIO     QUASAR_TIMER_SELECTION_TIMER4
#define QUASAR_DEF_TIMER_SELECTION_BLOCKING_DELAY  QUASAR_TIMER_SELECTION_TIMER2

/* MACROS *********************************************************************/
/*! Set a specific bit in a register. */
#define QUASAR_SET_BIT(REG, BIT_MASK) (REG |= (BIT_MASK))
/*! Clear a specific bit in a register. */
#define QUASAR_CLEAR_BIT(REG, BIT_MASK) (REG &= ~(BIT_MASK))
/*! Read a specific bit in a register at a given position. */
#define QUASAR_READ_BIT(REG, BIT_POS) ((REG >> BIT_POS) & 1)
/*! Write a specific value in specific bytes at a specific position. */
#define QUASAR_WRITE_BITS(BYTES, BITS_MASK, BITS_POS, VALUE) (BYTES |= (BITS_MASK & (VALUE << BITS_POS)))

/*
 * EXTI mapping:
 *
 * EXTI0:   User Button 4
 * EXTI1:   Audio codec IRQ -> Not used
 * EXTI2:
 * EXTI3:
 * EXTI4:   Line in detect
 * EXTI5:
 * EXTI6:
 * EXTI7:   Radio 2 IRQ
 * EXTI8:   Radio 1 IRQ
 * EXTI9:
 * EXTI10:  User Button 1
 * EXTI11:
 * EXTI12:  User Button 2
 * EXTI13:
 * EXTI14:
 * EXTI15:  User Button 3 || USB detect
 */

/*
 * Timer mapping:
 *                  BSP
 *  TIMER1 :
 *  TIMER2 :
 *  TIMER3 :
 *  TIMER4 :        Multi radio
 *  TIMER5 :
 *  TIMER6 :
 *  TIMER7 :
 *  TIMER8 :        Free running timer ms
 *  TIMER15 :
 *  TIMER16 :
 *  TIMER17 :
 */
#ifdef __cplusplus
}
#endif

#endif /* QUASAR_DEF_H_ */
